# Generated by Django 4.2.7 on 2024-03-02 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_edu", "0007_course_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_link",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="ссылка на оплату"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_link_expires_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="время окончания действия ссылки"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_status",
            field=models.SmallIntegerField(
                choices=[
                    (0, "Неизвестно"),
                    (1, "Ожидание оплаты"),
                    (2, "Оплачено"),
                    (3, "Отменено"),
                    (4, "Время ожидания истекло"),
                ],
                default=0,
                verbose_name="статус платежа",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Способ оплаты"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.CreateModel(
            name="StripeSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_session_id",
                    models.CharField(
                        max_length=150, verbose_name="идентификатор сессии Stripe"
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_payments.payment",
                        verbose_name="связанный платеж",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StripeProductCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_product_id",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="идентификатор товара в Stripe",
                    ),
                ),
                (
                    "stripe_default_price_id",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="идентификатор ценника в Stripe",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_edu.course",
                        verbose_name="курс",
                    ),
                ),
            ],
        ),
    ]
