# Generated by Django 4.2.7 on 2024-02-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_edu", "0002_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="courses",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="lessons",
                to="app_edu.course",
                verbose_name="Включен в курсы",
            ),
        ),
    ]
