# Generated by Django 4.2.7 on 2024-02-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_edu", "0003_alter_lesson_courses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="courses",
            field=models.ManyToManyField(
                blank=True,
                related_name="lessons",
                to="app_edu.course",
                verbose_name="Включен в курсы",
            ),
        ),
    ]
