# Generated by Django 4.2.7 on 2024-02-15 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_edu", "0001_initial"),
        ("app_users", "0003_purchasedproduct_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="purchased_product",
        ),
        migrations.AddField(
            model_name="payment",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app_edu.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app_edu.lesson",
                verbose_name="Урок",
            ),
        ),
        migrations.DeleteModel(
            name="PurchasedProduct",
        ),
    ]
