# Generated by Django 4.2.7 on 2024-02-19 10:48

from django.db import migrations, models
import utils.hash_storage


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0004_remove_payment_purchased_product_payment_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=utils.hash_storage.HashStorage(),
                upload_to=utils.hash_storage.user_avatar_images,
                verbose_name="Аватар",
            ),
        ),
    ]
