# Generated by Django 4.2.7 on 2024-03-01 07:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0005_alter_user_avatar"),
    ]

    database_operations = [
        migrations.AlterModelTable(
            name="Payment",
            table="app_payments_payment"
        ),
    ]

    state_operations = [
        migrations.DeleteModel(
            name="Payment"
        )
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations
        )
    ]
